config/routes.rb
Rails.application.routes.draw do
  root: "sessions#index"

  resources :posts

  get '/signup', to: "users#new"
  get '/profile', to: "users#show"

  resources :users, only: [:create]

  get '/login', to: "comments#new"
  get '/logout', to: "comments#destroy"

  resources :comments, only: [:create]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class Users < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
    user = User.find_by_email(user_params[:email])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to profile_path
    else
      redirect_to root_path
    end
  end

  # clear session (log out user)
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize, only: [:show]

	def create
    if current_user
      redirect_to profile_path
    else
      user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        # redirect_to '/profile'
        redirect_to profile_path
      else
        # redirect_to '/signup'
        redirect_to root_path
      end
    end
  end

  # show current_user
  def show
    @post = Post.all
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_login.html.erb
<!-- modal for sign up -->
<div class="modal fade" id="login-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Log In</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<%= form_for :user, url: sessions_path do |f| %>
					  <%= f.email_field :email, placeholder: "Email", class: "form-control"  %><br>
					  <%= f.password_field :password, placeholder: "Password", class: "form-control"  %><br>
					  <hr>
					  <%= f.submit "Log In" %>
					<% end %>
				</div>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/_new.html.erb
<!-- modal for sign up -->
<div class="modal fade" id="signup-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Sign Up to create your own Blog!</h4>
			</div>
			<div class="modal-body">
				<div class="form-group">
					<%= form_for :user do |f| %>
					<%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %><br>
					<%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %><br>
					<%= f.email_field :email, placeholder: "Email", class: "form-control" %><br>
					<%= f.password_field :password, placeholder: "Password", class: "form-control" %><br>
					<%= f.submit "Sign Up" %>
					<% end %>
				</div>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/show.html.erb
<% if current_user.comments.any? %>
<div class="col-md-12 text-center welcome-profile">
  <h1>Welcome <%= current_user.full_name %></h1>
  <h3>My Blog</h3>
  <div class="col-md-3"></div>
    <div class="col-md-6">
      <!-- comments post -->
      <%= render 'comments/post' %>
      <% else %>
        <div class="col-md-12 text-center empty-profile">
        <h4>You didn't type any new comments!</h4>
        <%= link_to "Add New ", new_comments_path %>
      <% end %>
    </div>
  <div class="col-md-3"></div>
</div>
</div>